name: damnit-web-dev

networks:
  proxy:
    external: true

services:
  app:
    build:
      dockerfile: ./apps/app/Dockerfile
      target: preview
      args:
        PREVIEW_PORT: ${APP_PREVIEW_PORT?}
        SITE_URL: https://damnit-test.xfel.eu
        API_URL: http://max-exfl463.desy.de:8123
    volumes:
      - ./certs:/certs
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.damnit_web_dev.rule=(Host(`damnit-dev.exfldadev01.desy.de`) || Host(`damnit-dev.xfel.eu`))"
      - "traefik.http.services.damnit_web_dev.loadbalancer.server.port=${APP_PREVIEW_PORT}"
    image: damnit-web-app:local
