name: damnit-web-prod

services:
  site:
    build:
      dockerfile: ./apps/site/Dockerfile
      target: build
      args:
        APP_URL: ${PUBLIC_URL?}${APP_BASE_PATH?}
        DEMO_URL: ${PUBLIC_URL?}${DEMO_BASE_PATH?}
    image: damnit-web-site:latest

  demo:
    build:
      dockerfile: ./apps/demo/Dockerfile
      target: build
      args:
        SITE_URL: ${PUBLIC_URL?}
        BASE_PATH: ${DEMO_BASE_PATH?}
    image: damnit-web-demo:latest

  app:
    build:
      dockerfile: ./apps/app/Dockerfile
      target: build
      args:
        SITE_URL: ${PUBLIC_URL?}
        BASE_PATH: ${APP_BASE_PATH?}
    image: damnit-web-app:latest

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      additional_contexts:
        site: "service:site"
        demo: "service:demo"
        app:  "service:app"
    depends_on:
      - site
      - demo
      - app
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_API_URL=${API_URL?}
      - NGINX_APP_BASE_PATH=${APP_BASE_PATH?}
      - NGINX_DEMO_BASE_PATH=${DEMO_BASE_PATH?}
    volumes:
      # # Certs used for mTLS
      # - ./certs:/etc/nginx/certs/mtls
      # Certs for serving
      - /data/certs/cert.key:/etc/nginx/certs/server.key
      - /data/certs/cert.pem:/etc/nginx/certs/server.crt
    ports:
      - 443:443
    restart: unless-stopped
    image: damnit-web-frontend:latest
