name: damnit-web-local

services:
  site:
    build:
      dockerfile: ./apps/site/Dockerfile
      target: preview
      args:
        PREVIEW_PORT: ${SITE_PREVIEW_PORT?}
        APP_URL: http://127.0.0.1:${APP_PREVIEW_PORT?}
    ports:
      - ${SITE_PREVIEW_PORT?}:${SITE_PREVIEW_PORT?}
    image: damnit-web-site:local

  app:
    build:
      dockerfile: ./apps/app/Dockerfile
      target: preview
      args:
        PREVIEW_PORT: ${APP_PREVIEW_PORT?}
        SITE_URL: http://127.0.0.1:${SITE_PREVIEW_PORT?}
        API_URL: ${API_URL}
    ports:
      - ${APP_PREVIEW_PORT?}:${APP_PREVIEW_PORT?}
    image: damnit-web-app:local
