name: damnit-web-prod

services:
  frontend:
    build:
      context: .
      target: production
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_API_URL=https://max-exfl458.desy.de:8123/
    ports:
      - 443:443
