name: damnit-web-prod

services:
  frontend:
    build:
      context: .
      target: production
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_API_URL=${NGINX_API_URL:?required}
    volumes:
      # Certs used for mTLS
      - ./certs:/etc/nginx/certs/mtls
      # Certs for serving
      - /data/certs/damnit.xfel.eu.key:/etc/nginx/certs/server.key
      - /data/certs/damnit.xfel.eu.pem:/etc/nginx/certs/server.crt
    ports:
      - 443:443
    restart: unless-stopped
