packages:
  - apps/*
  - packages/*

catalogs:
  components:
    '@glideapps/glide-data-grid': 6.0.3
    '@glideapps/glide-data-grid-cells': 6.0.3
    '@mantine/core': 7.17.3
    '@mantine/form': 7.17.3
    '@mantine/hooks': 7.17.3
    '@monaco-editor/react': 4.7.0
    '@tabler/icons-react': 3.31.0
    mantine-contextmenu: 7.17.1
    mantine-datatable: 7.17.1
    postcss-preset-mantine: 1.17.0
    react-plotly.js: 2.6.0
  frontend:
    clsx: 2.1.1
    dayjs: 1.11.13
    lodash: 4.17.23
    react: 18.2.0
    react-dom: 18.2.0
    react-laag: 2.0.5
    react-router: 7.9.6
  graphql:
    '@apollo/client': 3.13.6
    graphql: 16.10.0
    graphql-ws: 6.0.4
  linting:
    '@eslint/js': 9.22.0
    eslint: 9.22.0
    eslint-config-prettier: 10.1.1
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.19
    globals: 16.0.0
    prettier: 3.6.2
    typescript-eslint: 8.46.4
  redux:
    '@reduxjs/toolkit': 2.6.1
    react-redux: 9.2.0
  tooling:
    '@vitejs/plugin-react': 5.1.0
    postcss: 8.5.3
    postcss-simple-vars: 7.0.1
    typescript: 5.9.3
    vite: 7.2.2
  types:
    '@types/lodash': 4.17.23
    '@types/node': 24.10.0
    '@types/react': 18.2.45
    '@types/react-dom': 18.2.18
    '@types/react-plotly.js': 2.6.3
