packages:
  - "apps/*"
  - "packages/*"

catalogs:
  frontend:
    react: 18.2.0
    react-dom: 18.2.0
    react-router: 7.9.6
    clsx: 2.1.1
    dayjs: 1.11.13
    react-laag: 2.0.5

  components:
    "@mantine/core": 7.17.3
    "@mantine/form": 7.17.3
    "@mantine/hooks": 7.17.3
    mantine-contextmenu: 7.17.1
    mantine-datatable: 7.17.1
    "@monaco-editor/react": 4.7.0
    "@glideapps/glide-data-grid": 6.0.3
    "@glideapps/glide-data-grid-cells": 6.0.3
    "@tabler/icons-react": 3.31.0
    "react-plotly.js": 2.6.0
    "postcss-preset-mantine": 1.17.0

  graphql:
    "@apollo/client": 3.13.6
    graphql: 16.10.0
    graphql-ws: 6.0.4

  redux:
    "@reduxjs/toolkit": 2.6.1
    react-redux: 9.2.0
    "react-redux-loading-bar": 5.0.8

  tooling:
    typescript: 5.9.3
    vite: 7.2.2
    "@vitejs/plugin-react": 5.1.0
    postcss: 8.5.3
    "postcss-simple-vars": 7.0.1

  linting:
    eslint: 9.22.0
    "@eslint/js": 9.22.0
    eslint-config-prettier: 10.1.1
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.19
    prettier: 3.6.2
    globals: 16.0.0
    typescript-eslint: 8.46.4

  types:
    "@types/node": 24.10.0
    "@types/react": 18.2.45
    "@types/react-dom": 18.2.18
    "@types/react-plotly.js": 2.6.3
