name: damnit-web-dev

services:
  api:
    userns_mode: host
    ports:
      - 8123:8000
    volumes:
      - ./certs:/certs
      - /gpfs/exfel/data/scratch/xdana/tmp/damnit-web:/var/tmp
      - /gpfs:/gpfs
      - /pnfs:/pnfs
