name: damnit-web-test

services:
  api:
    build: .
    volumes:
      - ./db:/db
      - /gpfs:/gpfs:ro
      - /pnfs:/pnfs:ro
    env_file:
      - .env
    environment:
      - DW_API_DB_PATH=/db/dw_api.sqlite
      - DW_API_UVICORN__HOST=0.0.0.0
      - DW_API_UVICORN__PORT=8443
    ports:
      - 8543:8443
    restart: unless-stopped
