name: damnit-web-local

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      DW_API_UVICORN__SSL_CERTFILE: /certs/server.crt
      DW_API_UVICORN__SSL_KEYFILE: /certs/server.key
      DW_API_UVICORN__SSL_CA_CERTS: /certs/root_ca.crt
    volumes:
      - ./tmp-damnit-web/:/tmp/damnit-web/
      - ./certs:/certs
