name: damnit-web-local

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      DW_API_MTLS__CLIENT_CERT: /certs/server.crt
      DW_API_MTLS__CLIENT_KEY: /certs/server.key
      DW_API_MTLS__ROOT_CERT: /certs/root_ca.crt
    volumes:
      - ./tmp-damnit-web/:/tmp/damnit-web/
      - ./certs:/certs
